server:
  port: 8081
spring:
  application:
    name: consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.kafka.consumer.model.RiderLocation




#  Config Key                                     What It Does
#  key-deserializer                              Tells Kafka how to convert the message key from bytes back to a String
#  value-deserializer                            Uses an error-handling wrapper to safely convert the message value from JSON


#  🔹 spring.deserializer.value.delegate.class
#💬 Meaning:
#  "Use this deserializer to convert JSON into Java objects."
#
#  ✅ You're telling Spring to use JsonDeserializer (from Spring Kafka) to turn the message's JSON into your Java class.



#  🔹 spring.json.value.default.type
#💬 Meaning:
#  "Always convert the JSON into this specific Java class."
#
#✅ Here, you're saying:
#  "Treat the incoming JSON as a RiderLocation object."


#  🔹 spring.json.trusted.packages
#💬 Meaning:
#  "Trust classes from these packages when converting JSON to Java objects."
#
#✅ Setting it to "*" means:
#  "Trust any package."
#  (It works, but it's safer to name only the packages you expect.)