spring:
  application:
    name: order-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name: order_topics
## producer is connecting to the kafka server (kafka broker)
## we  convert the key into a byte stream before sending it to the Kafka topic.
## Kafka uses this serializer to convert Java objects into JSON before sending them to the Kafka topic.